"""is_verified

Revision ID: 0835112a1c8c
Revises: 1bcf059279ef
Create Date: 2022-12-04 13:40:36.421794

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0835112a1c8c'
down_revision = '1bcf059279ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
