"""updated

Revision ID: 089cf1c5719e
Revises: 0ccaca090e69
Create Date: 2022-11-16 14:02:23.482421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '089cf1c5719e'
down_revision = '0ccaca090e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
