"""updated product table

Revision ID: 39afd6b4109f
Revises: 750a296560c3
Create Date: 2022-12-12 14:21:05.014721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '39afd6b4109f'
down_revision = '750a296560c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('image1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cart', sa.Column('image2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cart', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('image1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('image2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    op.drop_column('product', 'image2')
    op.drop_column('product', 'image1')
    op.drop_column('cart', 'description')
    op.drop_column('cart', 'image2')
    op.drop_column('cart', 'image1')
    # ### end Alembic commands ###
