"""is_verified

Revision ID: 73767965ca3d
Revises: 0835112a1c8c
Create Date: 2022-12-04 13:54:23.115368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '73767965ca3d'
down_revision = '0835112a1c8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
