"""cart table updated

Revision ID: 750a296560c3
Revises: 1c50cf848878
Create Date: 2022-12-12 12:55:13.082567

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '750a296560c3'
down_revision = '1c50cf848878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_user_email_key', 'cart', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_user_email_key', 'cart', ['user_email'])
    # ### end Alembic commands ###
