"""product table

Revision ID: c550765c2bd8
Revises: d0582d4c851a
Create Date: 2022-11-23 13:35:47.630539

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c550765c2bd8'
down_revision = 'd0582d4c851a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
